name:                menu
version:             0.0.0.1
#synopsis:
#description:
homepage:            https://github.com/githubuser/menu#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:
    - src

executables:
  menu:
    source-dirs:      app
    main:             Main.hs
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - menu

tests:
  menu-test:
    source-dirs:      test
    main:             Spec.hs
    ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - menu
      - hspec
      - QuickCheck

github: githubuser/menu
